namespace Amazon.Runtime
{
	public enum Metric
	{
		AWSErrorCode,
		AWSRequestID,
		AmzId2,
		BytesProcessed,
		Exception,
		RedirectLocation,
		ResponseProcessingTime,
		ResponseUnmarshallTime,
		ResponseReadTime,
		StatusCode,
		AttemptCount,
		CredentialsRequestTime,
		HttpRequestTime,
		ProxyHost,
		ProxyPort,
		RequestSigningTime,
		RetryPauseTime,
		StringToSign,
		CanonicalRequest,
		AsyncCall,
		ClientExecuteTime,
		MethodName,
		ServiceEndpoint,
		ServiceName,
		RequestSize,
		AmzCfId
	}
}
